<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    public $directory='/images/';
    protected $dates=['deleted_at'];
    protected $fillable =['title','content'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function photos()
    {
        return $this->morphMany(Photo::class,'imageable');
    }
    public function tags()
    {
        return $this->morphToMany('App\Tag', 'taggable');
    }
    public function __call($method, $parameters)
    {
        return parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
//Accessor
    public function getTitleAttribute($value)
    {
//        return ucfirst($value);
        return strtoupper($value);
    }
//Mutator
    public function setTitleAttribute($value)
    {
    $this->attributes['title']=strtoupper($value);
    }

    public function getPathAttribute($value)
    {
        return $this->directory.$value;
    }

}
